### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by naruhaxor** [isaacgravenortechnologies/source-vita#1]
idk if this is my side but i wanted to see if this would even compile and it doesnt
![image](https://github.com/isaacgravenortechnologies/source-vita/assets/13723543/2a9cd598-e12d-4ab5-84b2-21c90227673a)

**Comment by isaacgravenortechnologies** [comment]
It comes nowhere near to compiling yet, im restarting the project with the original source code from nillerusr again, then I will add  vita compiling, using vitasdk and vdpm. Will close as not planned until I finish the first working build.
